# Generated by Django 4.0.3 on 2022-03-28 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptreal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yellowcard', models.CharField(max_length=50)),
                ('yellowcardnumber', models.CharField(max_length=50)),
                ('why', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=50)),
                ('varity', models.CharField(max_length=50)),
                ('userwho', models.CharField(max_length=50)),
                ('petname', models.CharField(max_length=50)),
                ('petsex', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='image/')),
                ('phonenumber', models.IntegerField()),
            ],
            options={
                'db_table': 'adoptreal',
            },
        ),
        migrations.CreateModel(
            name='Helpreal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(default=django.utils.timezone.now)),
                ('where', models.CharField(max_length=50)),
                ('petname', models.CharField(max_length=50)),
                ('varity', models.CharField(max_length=50)),
                ('yellowcard', models.CharField(max_length=50)),
                ('yellowcardnumber', models.CharField(max_length=50)),
                ('special', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='image/')),
                ('phonenumber', models.IntegerField()),
            ],
            options={
                'db_table': 'helpreal',
            },
        ),
    ]
