# Generated by Django 4.0.3 on 2022-03-28 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_adoptreal_helpreal'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adoptreal',
            table=None,
        ),
        migrations.AlterModelTable(
            name='helpreal',
            table=None,
        ),
    ]
